"""empty message

Revision ID: 062566abc924
Revises: 9b1b67a78b2c
Create Date: 2024-04-19 14:25:46.842525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '062566abc924'
down_revision = '9b1b67a78b2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=True))

    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.alter_column('video_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.alter_column('post_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.alter_column('post_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.alter_column('video_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('content')

    # ### end Alembic commands ###
